### ntb_etl_tratamento.ipynb

Notebook responsável por realizar o tratamento da base de jogos e exportar uma tabela confiável para treinamento do modelo de predição

In [135]:
import pandas as pd

In [136]:
pd.set_option('display.max_columns', None)
base_raw = pd.read_csv('../data/raw/base_partidas_raw.csv')
base_raw.head()

,id,date,status_id,tournament.id,tournament.token,tournament.token_international,tournament.status_id,console.id,console.token,console.token_international,participant1.id,participant1.nickname,participant1.score,participant1.photo,participant1.team.logo,participant1.team.id,participant1.team.token,participant1.team.token_international,participant1.prevPeriodsScores,participant2.id,participant2.nickname,participant2.score,participant2.photo,participant2.team.logo,participant2.team.id,participant2.team.token,participant2.team.token_international,participant2.prevPeriodsScores
0,1404256,2025-01-01T11:50:00Z,3,181773,Лига чемпионов А 2х6 2025-01-01,Champions League A 2x6 2025-01-01,4,136,Anfield-1,Anfield-1,603262,flamez,3,L2dhbWVycy81LzUzLzUzOS8xNzAwNTk0MDE4LXBob3RvLm...,L3RlYW1zLzIvMjEvMjEvbG9nby5wbmc=,21,Пари Сен Жермен,Paris Saint-Germain F.C.,['1'],603265,Kinshiki,3,L2dhbWVycy81LzU1LzU1OS8xNzA1NTk5NDkyLXBob3RvLm...,L3RlYW1zLzYvNi82L2xvZ28ucG5n,6,Манчестер Сити,Manchester City,['2']
1,1404257,2025-01-01T11:50:00Z,3,181773,Лига чемпионов А 2х6 2025-01-01,Champions League A 2x6 2025-01-01,4,137,Anfield-2,Anfield-2,603263,qqvlone,2,L2dhbWVycy81LzU1LzU1Ni8xNzA1NTk5NDIzLXBob3RvLm...,L3RlYW1zLzIvMjAvMjAvbG9nby5wbmc=,20,Реал Мадрид,Real Madrid,['1'],603264,Decade,4,L2dhbWVycy81LzU2LzU2Ni8xNzA5NTcwMTcxLXBob3RvLm...,L3RlYW1zLzIvMi8yLzE2OTE1ODQ4NjMtbG9nby5wbmc=,2,Ливерпуль,Liverpool,['2']
2,1404258,2025-01-01T12:08:00Z,3,181773,Лига чемпионов А 2х6 2025-01-01,Champions League A 2x6 2025-01-01,4,136,Anfield-1,Anfield-1,603264,Decade,4,L2dhbWVycy81LzU2LzU2Ni8xNzA5NTcwMTcxLXBob3RvLm...,L3RlYW1zLzIvMi8yLzE2OTE1ODQ4NjMtbG9nby5wbmc=,2,Ливерпуль,Liverpool,['2'],603262,flamez,3,L2dhbWVycy81LzUzLzUzOS8xNzAwNTk0MDE4LXBob3RvLm...,L3RlYW1zLzIvMjEvMjEvbG9nby5wbmc=,21,Пари Сен Жермен,Paris Saint-Germain F.C.,['1']
3,1404259,2025-01-01T12:08:00Z,3,181773,Лига чемпионов А 2х6 2025-01-01,Champions League A 2x6 2025-01-01,4,137,Anfield-2,Anfield-2,603265,Kinshiki,4,L2dhbWVycy81LzU1LzU1OS8xNzA1NTk5NDkyLXBob3RvLm...,L3RlYW1zLzYvNi82L2xvZ28ucG5n,6,Манчестер Сити,Manchester City,['4'],603266,SpeciAL,6,L2dhbWVycy81LzU0LzU0OC8xNzAwNTkzODg0LXBob3RvLm...,L3RlYW1zLzkvOS85L2xvZ28ucG5n,9,Бавария,Bayern Munich,['3']
4,1404260,2025-01-01T12:26:00Z,3,181773,Лига чемпионов А 2х6 2025-01-01,Champions League A 2x6 2025-01-01,4,136,Anfield-1,Anfield-1,603266,SpeciAL,1,L2dhbWVycy81LzU0LzU0OC8xNzAwNTkzODg0LXBob3RvLm...,L3RlYW1zLzkvOS85L2xvZ28ucG5n,9,Бавария,Bayern Munich,['1'],603264,Decade,3,L2dhbWVycy81LzU2LzU2Ni8xNzA5NTcwMTcxLXBob3RvLm...,L3RlYW1zLzIvMi8yLzE2OTE1ODQ4NjMtbG9nby5wbmc=,2,Ливерпуль,Liverpool,['1']

#### Filtra as tabelas necessárias

In [137]:
base_copy = base_raw.copy() # Cria cópia da base

base_filtered = base_copy[
    [
        'id', 
        'date',
        'tournament.id', 
        'tournament.token_international', 
        'console.id', 
        'console.token',
        'console.token_international',
        'participant1.id',
        'participant1.nickname',
        'participant1.score',
        'participant1.team.id',
        'participant1.team.token_international',
        'participant2.id',
        'participant2.nickname',
        'participant2.score',
        'participant2.team.id',
        'participant2.team.token_international'
    ]
]

#### Renomeia o estádios que vieram com nomes errados

In [138]:
rename_estadios = {            # Renomeando o nome dos estádios que faltaram
    '1': 'Old Trafford',
    '2': 'Old Trafford',
    '3': 'Wembley',
    '4': 'Wembley',
    'console-12': 'Stamford Bridge',
    'console-11': 'Stamford Bridge'
}

base_filtered["console.token_international"] = (
    base_filtered["console.token_international"].replace(rename_estadios)
)

C:\Users\Windows\AppData\Local\Temp\ipykernel_19636\3911453634.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_filtered["console.token_international"] = (

In [139]:
# estadios = base_filtered[['console.id','console.token', 'console.token_international']].drop_duplicates()
# estadios

#### Cria as colunas de Data e Hora

In [140]:
# Cria coluna Data
base_filtered.loc[:, 'data'] = (
    pd.to_datetime(base_filtered['date'].str.split('T').str[0], errors='coerce')
      .dt.strftime('%d/%m/%Y')
)

# Cria coluna Hora
hora_brt_dt = pd.to_datetime(base_filtered['date'], errors='coerce').dt.floor('min')

# Cria coluna hora_uk (3hrs atrás da brt)
hora_uk_dt = hora_brt_dt - pd.Timedelta(hours=3)

# 5) Format
base_filtered.loc[:, 'hora_brt'] = hora_brt_dt.dt.strftime('%H:%M')
base_filtered.loc[:, 'hora_us']  = hora_uk_dt.dt.strftime('%H:%M')

C:\Users\Windows\AppData\Local\Temp\ipykernel_19636\2663680631.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_filtered.loc[:, 'data'] = (
C:\Users\Windows\AppData\Local\Temp\ipykernel_19636\2663680631.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_filtered.loc[:, 'hora_brt'] = hora_brt_dt.dt.strftime('%H:%M')
C:\Users\Windows\AppData\Local\Temp\ipykernel_19636\2663680631.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_filtered.loc[:, 'hora_us']  = hora_uk_dt.dt.strftime('%H:%M')

In [141]:
base_filtered.head()

,id,date,tournament.id,tournament.token_international,console.id,console.token,console.token_international,participant1.id,participant1.nickname,participant1.score,participant1.team.id,participant1.team.token_international,participant2.id,participant2.nickname,participant2.score,participant2.team.id,participant2.team.token_international,data,hora_brt,hora_us
0,1404256,2025-01-01T11:50:00Z,181773,Champions League A 2x6 2025-01-01,136,Anfield-1,Anfield-1,603262,flamez,3,21,Paris Saint-Germain F.C.,603265,Kinshiki,3,6,Manchester City,01/01/2025,11:50,08:50
1,1404257,2025-01-01T11:50:00Z,181773,Champions League A 2x6 2025-01-01,137,Anfield-2,Anfield-2,603263,qqvlone,2,20,Real Madrid,603264,Decade,4,2,Liverpool,01/01/2025,11:50,08:50
2,1404258,2025-01-01T12:08:00Z,181773,Champions League A 2x6 2025-01-01,136,Anfield-1,Anfield-1,603264,Decade,4,2,Liverpool,603262,flamez,3,21,Paris Saint-Germain F.C.,01/01/2025,12:08,09:08
3,1404259,2025-01-01T12:08:00Z,181773,Champions League A 2x6 2025-01-01,137,Anfield-2,Anfield-2,603265,Kinshiki,4,6,Manchester City,603266,SpeciAL,6,9,Bayern Munich,01/01/2025,12:08,09:08
4,1404260,2025-01-01T12:26:00Z,181773,Champions League A 2x6 2025-01-01,136,Anfield-1,Anfield-1,603266,SpeciAL,1,9,Bayern Munich,603264,Decade,3,2,Liverpool,01/01/2025,12:26,09:26

#### Renomeia as colunas da tabela

In [142]:
renamed_columns = {

    'date': 'datetime',
    'tournament.id': 'id_torneio',
    'tournament.token_international': 'nome_torneio',
    'console.id': 'id_estadio',
    'console.token': 'token_estadio',
    'console.token_international': 'nome_estadio',
    'participant1.id': 'id_player_casa',
    'participant1.nickname': 'nome_player_casa',
    'participant1.score': 'gols_casa',
    'participant1.team.id': 'id_time_casa',
    'participant1.team.token_international': 'nome_time_casa',
    'participant2.id': 'id_player_fora',
    'participant2.nickname': 'nome_player_fora',
    'participant2.score': 'gols_fora',
    'participant2.team.id': 'id_time_fora',
    'participant2.team.token_international': 'nome_time_fora'

}

base_renamed = base_filtered.rename(columns=renamed_columns)

#### Calcula o total de gols e over x gols

In [143]:
# Coluna Resultado
base_renamed['resultado'] = base_renamed.apply(
    lambda row: 'casa' if row['gols_casa'] > row['gols_fora']
    else 'fora' if row['gols_casa'] < row['gols_fora']
    else 'empate',
    axis=1
)

# Total de gols
base_renamed['gols_total'] = base_renamed['gols_casa'] + base_renamed['gols_fora']

# # Over Gols
# base_renamed['over_0_5'] = (base_renamed['gols_total'] > 0.5).astype(int)
# base_renamed['over_1_5'] = (base_renamed['gols_total'] > 1.5).astype(int)
# base_renamed['over_2_5'] = (base_renamed['gols_total'] > 2.5).astype(int)
# base_renamed['over_3_5'] = (base_renamed['gols_total'] > 3.5).astype(int)

#### ID resultado

In [144]:
map_resultado = {'casa': 1, 'empate': 0, 'fora': 2}
base_renamed['id_resultado'] = base_renamed['resultado'].map(map_resultado)

In [145]:
# base_renamed.head()

#### Export base full tratada

In [146]:
# # Export base total
# base_renamed.to_csv('../data/trusted/base_partidas_trusted.csv', index=False, encoding='utf-8')

#### Export base numerica

In [147]:
# # Export base sem features não numéricas
# base_numerica = base_renamed.drop(['datetime', 'id_torneio', 'id_estadio', 'nome_torneio', 'token_estadio',
#                                     'nome_estadio', 'nome_player_casa', 'nome_time_casa',
#                                     'nome_player_fora', 'nome_time_fora', 'data', 'hora_brt',
#                                     'hora_us', 'resultado'], axis=1)
# base_numerica.to_csv('../data/trusted/base_numerica_trusted.csv', index=False, encoding='utf-8')

#### Export tabela de times

In [148]:
# base_times_casa = (base_renamed[['id_time_casa', 'nome_time_casa', 'gols_casa']]
#                    .rename(columns={
#                        'id_time_casa': 'id_time',
#                        'nome_time_casa': 'nome_time',
#                        'gols_casa': 'gols'
#                    })
#                    )
                   
# base_times_fora = (base_renamed[['id_time_fora', 'nome_time_fora', 'gols_fora']]
#                    .rename(columns={
#                        'id_time_fora': 'id_time',
#                        'nome_time_fora': 'nome_time',
#                        'gols_fora': 'gols'
#                    })
#                    )

# base_times = pd.concat([base_times_casa, base_times_fora], ignore_index=True)
# base_times = (
#     base_times.groupby(['id_time', 'nome_time'], as_index=False)
#     .agg(
#         gols = ('gols', 'sum')
#     )
#     .sort_values('gols', ascending=False)
#     .reset_index(drop=True)
# )

# base_times = pd.concat([base_times_casa, base_times_fora], ignore_index=True)
# base_times = (
#     base_times.groupby(['id_time', 'nome_time'], as_index=False)
#     .agg(
#         gols = ('gols', 'sum')
#     )
#     .sort_values('gols', ascending=False)
#     .reset_index(drop=True)
# )

# base_times.to_csv('../data/trusted/dm_times.csv', index=False, encoding='utf-8')

In [149]:
base_renamed.head(1)

,id,datetime,id_torneio,nome_torneio,id_estadio,token_estadio,nome_estadio,id_player_casa,nome_player_casa,gols_casa,id_time_casa,nome_time_casa,id_player_fora,nome_player_fora,gols_fora,id_time_fora,nome_time_fora,data,hora_brt,hora_us,resultado,gols_total,id_resultado
0,1404256,2025-01-01T11:50:00Z,181773,Champions League A 2x6 2025-01-01,136,Anfield-1,Anfield-1,603262,flamez,3,21,Paris Saint-Germain F.C.,603265,Kinshiki,3,6,Manchester City,01/01/2025,11:50,08:50,empate,6,0

#### Export tabela Jogadores

In [ ]:
jogadores_casa = (
    base_renamed[['id_player_casa', 'nome_player_casa', 'gols_casa']]
    .rename(columns={
        'id_player_casa': 'id_player',
        'nome_player_casa': 'nome_player',
        'gols_casa': 'gols'
    })
)

jogadores_fora = (
    base_renamed[['id_player_fora', 'nome_player_fora', 'gols_fora']]
    .rename(columns={
        'id_player_fora': 'id_player',
        'nome_player_fora': 'nome_player',
        'gols_fora': 'gols'
    })
)

# Junta casa + fora
base_jogadores = pd.concat([jogadores_casa, jogadores_fora], ignore_index=True)

# Agrupa só pelo nome do jogador → soma gols e conta partidas
base_jogadores = (
    base_jogadores.groupby('nome_player', as_index=False)
    .agg(
        gols=('gols', 'sum'),
        partidas=('gols', 'size')
    )
    .sort_values('gols', ascending=False)
    .reset_index(drop=True)
)

# Se quiser criar um id artificial único
base_jogadores['id_player'] = base_jogadores.index + 1

# Ordem desejada (id primeiro, depois o resto)
cols = ['id_player', 'nome_player', 'gols', 'partidas']

# Reorganiza o DataFrame
base_jogadores = base_jogadores[['id_player', 'nome_player', 'gols', 'partidas']]

base_jogadores.to_csv('../data/trusted/dm_jogadores.csv', index=False, encoding='utf-8')

In [152]:
base_renamed.head()

,id,datetime,id_torneio,nome_torneio,id_estadio,token_estadio,nome_estadio,id_player_casa,nome_player_casa,gols_casa,id_time_casa,nome_time_casa,id_player_fora,nome_player_fora,gols_fora,id_time_fora,nome_time_fora,data,hora_brt,hora_us,resultado,gols_total,id_resultado
0,1404256,2025-01-01T11:50:00Z,181773,Champions League A 2x6 2025-01-01,136,Anfield-1,Anfield-1,603262,flamez,3,21,Paris Saint-Germain F.C.,603265,Kinshiki,3,6,Manchester City,01/01/2025,11:50,08:50,empate,6,0
1,1404257,2025-01-01T11:50:00Z,181773,Champions League A 2x6 2025-01-01,137,Anfield-2,Anfield-2,603263,qqvlone,2,20,Real Madrid,603264,Decade,4,2,Liverpool,01/01/2025,11:50,08:50,fora,6,2
2,1404258,2025-01-01T12:08:00Z,181773,Champions League A 2x6 2025-01-01,136,Anfield-1,Anfield-1,603264,Decade,4,2,Liverpool,603262,flamez,3,21,Paris Saint-Germain F.C.,01/01/2025,12:08,09:08,casa,7,1
3,1404259,2025-01-01T12:08:00Z,181773,Champions League A 2x6 2025-01-01,137,Anfield-2,Anfield-2,603265,Kinshiki,4,6,Manchester City,603266,SpeciAL,6,9,Bayern Munich,01/01/2025,12:08,09:08,fora,10,2
4,1404260,2025-01-01T12:26:00Z,181773,Champions League A 2x6 2025-01-01,136,Anfield-1,Anfield-1,603266,SpeciAL,1,9,Bayern Munich,603264,Decade,3,2,Liverpool,01/01/2025,12:26,09:26,fora,4,2